(ns slopp.build
  "The native-binary build target (O4): pure generators for everything an
  explicit `build!` needs to compile a store-built project into a
  self-contained executable via GraalVM native-image.

  The generated launcher uses `gen-class` — legal here because the D3/D4
  dialect gates *authored store code*; build output is host-generated
  scaffolding, the same standing as slopp.rt's instrumentation machinery.
  The dialect is also what makes this target reliable: the bans on
  eval/read-string/gen-class/user-macros are exactly the closed-world
  assumptions native-image needs.

  Recipe per clj-easy/graal-docs current practice: AOT-compile with direct
  linking, put com.github.clj-easy/graal-build-time on the classpath (its
  Feature registers Clojure classes for build-time init), `--no-fallback`."
  (:require [clojure.string :as str]))

(defn arg-style
  "How the launcher hands CLI args to the entry fn, judged from its index
  var-definition: a single fixed arity of 1 (and no varargs) receives the
  args as ONE vector; every other shape is `apply`'d, -main style."
  [{:keys [fixed-arities varargs-min-arity]}]
  (if (and (nil? varargs-min-arity) (= #{1} (set fixed-arities)))
    :vector
    :apply))

(defn launcher-source
  "The generated `src/native/main.clj`: a gen-class entry delegating to
  `main-sym`, exiting cleanly (flush + shutdown-agents, so a lingering agent
  thread pool can't hang the binary)."
  [main-sym style]
  (str "(ns native.main\n"
       "  \"Generated by slopp build! — do not edit; rebuild instead.\"\n"
       "  (:require [" (namespace main-sym) "])\n"
       "  (:gen-class))\n"
       "\n"
       "(defn -main [& args]\n"
       (case style
         :vector (str "  (" main-sym " (vec args))\n")
         :apply  (str "  (apply " main-sym " args)\n"))
       "  (flush)\n"
       "  (shutdown-agents))\n"))

^:unsafe (defn deps-edn
  "deps.edn for the built project; `deps` (lib→coord, the store's Tier-1
  manifest) becomes the `:deps` map so a built project is runnable; with
  `native?`, adds the :native alias (AOT output path, graal-build-time, direct
  linking) — manifest deps flow to the native classpath via `-Spath -A:native`;
  with `test?`, adds a `:test` alias putting `test/` on an extra-path AND
  carrying the cognitect test-runner, so `clojure -M:test` runs the project's
  suite out of the box (the isolated runner builds+runs exactly this). With an
  EMPTY manifest and no test/native aliases the
  output is byte-identical to the pre-manifest version (the build! `ours?`
  byte-identity guard relies on this)."
  ([native?] (deps-edn native? {}))
  ([native? deps] (deps-edn native? deps false))
  ([native? deps test?]
   ;; bind *print-namespace-maps* OFF: it defaults true at a REPL, false in a
   ;; script — leaving it would make output non-deterministic (the git
   ;; projection + build! ours? guard both depend on byte-stable output).
   (let [deps-str (if (seq deps)
                    (str " :deps " (binding [*print-namespace-maps* false]
                                     (pr-str deps)))
                    "")
         ;; each alias entry is "KEY\n  {VALUE}"; the first sits right after the
         ;; aliases-map `{` (matching the historical single-:native layout), the
         ;; rest are 2-space-indented — order is deterministic (test, native).
         aliases  (cond-> []
                    test?   (conj (str ":test\n"
                                       "  {:extra-paths [\"test\"]\n"
                                       "   :extra-deps  {io.github.cognitect-labs/test-runner\n"
                                       "                 {:git/tag \"v0.5.1\" :git/sha \"dfb30dd\"}}\n"
                                       "   :main-opts   [\"-m\" \"cognitect.test-runner\"\n"
                                       "                 \"-d\" \"test\" \"-d\" \"src\" \"-r\" \".*\"]}"))
                    native? (conj (str ":native\n"
                                       "  {:extra-paths [\"classes\"]\n"
                                       "   :extra-deps  {com.github.clj-easy/graal-build-time {:mvn/version \"1.0.5\"}}\n"
                                       "   :jvm-opts    [\"-Dclojure.compiler.direct-linking=true\"]}")))]
     (if (empty? aliases)
       (str "{:paths [\"src\"]" deps-str "}\n")
       (str "{:paths [\"src\"]" deps-str "\n"
            " :aliases\n"
            " {" (str/join "\n  " aliases) "}}\n")))))

(defn native-script
  "build-native.sh: AOT-compile the launcher (and, transitively, the app),
  then native-image the result into `bin-name`."
  [bin-name]
  (str "#!/usr/bin/env bash\n"
       "# Generated by slopp build! — compiles this project to a native binary.\n"
       "# Needs GraalVM 21+ on PATH (native-image ships inside the JDK; no gu).\n"
       "set -euo pipefail\n"
       "cd \"$(dirname \"$0\")\"\n"
       "\n"
       "command -v native-image >/dev/null 2>&1 || {\n"
       "  echo \"native-image not found — install GraalVM 21+ (e.g.\" >&2\n"
       "  echo \"mise install java@graalvm-community-21, or graalvm.org)\" >&2\n"
       "  exit 1\n"
       "}\n"
       "\n"
       "mkdir -p classes\n"
       "clojure -M:native -e \"(compile 'native.main)\"\n"
       "\n"
       "native-image \\\n"
       "  -cp \"classes:$(clojure -Spath -A:native)\" \\\n"
       "  -o \"" bin-name "\" \\\n"
       "  --no-fallback \\\n"
       "  --features=clj_easy.graal_build_time.InitClojureClasses \\\n"
       "  native.main\n"
       "\n"
       "echo \"built ./" bin-name "\"\n"))
