(ns slopp.build
  "The native-binary build target (O4): pure generators for everything an
  explicit `build!` needs to compile a store-built project into a
  self-contained executable via GraalVM native-image.

  The generated launcher uses `gen-class` — legal here because the D3/D4
  dialect gates *authored store code*; build output is host-generated
  scaffolding, the same standing as slopp.rt's instrumentation machinery.
  The dialect is also what makes this target reliable: the bans on
  eval/read-string/gen-class/user-macros are exactly the closed-world
  assumptions native-image needs.

  Recipe per clj-easy/graal-docs current practice: AOT-compile with direct
  linking, put com.github.clj-easy/graal-build-time on the classpath (its
  Feature registers Clojure classes for build-time init), `--no-fallback`."
  (:require [clojure.string :as str]))

(defn ^{:foreign-keys true
        :malli/schema [:=> [:cat [:map
                                  [:fixed-arities {:optional true} [:maybe [:set :int]]]
                                  [:varargs-min-arity {:optional true} [:maybe :int]]]]
                       [:enum :vector :apply]]}
  arg-style
  "How the launcher hands CLI args to the entry fn, judged from its index
  var-definition: a single fixed arity of 1 (and no varargs) receives the
  args as ONE vector; every other shape is `apply`'d, -main style.

  The arg is clj-kondo's var-definition map, hence `^:foreign-keys` — its
  spelling is not ours to change. The `:=>` schema is generatively checked
  (this fn is referentially transparent), so it states the real shape."
  [{:keys [fixed-arities varargs-min-arity]}]
  (if (and (nil? varargs-min-arity) (= #{1} (set fixed-arities)))
    :vector
    :apply))

(defn launcher-source
  "The generated `src/native/main.clj`: a gen-class entry delegating to
  `main-sym`, exiting cleanly (flush + shutdown-agents, so a lingering agent
  thread pool can't hang the binary)."
  [main-sym style]
  (str "(ns native.main\n"
       "  \"Generated by slopp build! — do not edit; rebuild instead.\"\n"
       "  (:require [" (namespace main-sym) "])\n"
       "  (:gen-class))\n"
       "\n"
       "(defn -main [& args]\n"
       (case style
         :vector (str "  (" main-sym " (vec args))\n")
         :apply  (str "  (apply " main-sym " args)\n"))
       "  (flush)\n"
       "  (shutdown-agents))\n"))

(defn- coerce-exclusions
  "tools.deps requires a coord's `:exclusions` to be SYMBOLS; an MCP-supplied
  coord carries them as strings (JSON has no symbol type). Coerce each so the
  projected deps.edn resolves — a string exclusion makes make_classpath2 fail
  in every fresh JVM (build, external test tier, native), while the live
  hot-add tolerates it."
  [deps]
  (into {}
        (map (fn [[lib coord]]
               [lib (cond-> coord
                      (:exclusions coord)
                      (update :exclusions
                              (fn [xs] (mapv #(if (string? %) (symbol %) %) xs))))]))
        deps))

(defn client-compiler
  "The configured client-side compiler for `store` (D-web-cljs) — read from the
  `client` config file's `compiler` key, defaulting to :clojurescript. The
  compile step DISPATCHES on this, so cherry/squint can be plugged in per
  project (`config_file {path \"client\" key \"compiler\" value \"cherry\"}`)
  without re-authoring a single stored form — the `.cljs`/`.cljc` source is
  compiler-agnostic. Only :clojurescript is implemented today."
  [store]
  (keyword (or (get-in store [:config "client" :values "compiler"])
               "clojurescript")))

^:unsafe (defn deps-edn
  "deps.edn for the built project; `deps` (lib→coord, the store's Tier-1
  manifest) becomes the `:deps` map so a built project is runnable; with
  `native?`, adds the :native alias (AOT output path, graal-build-time, direct
  linking) — manifest deps flow to the native classpath via `-Spath -A:native`;
  with `test?`, adds a `:test` alias putting `test/` on an extra-path AND
  carrying the cognitect test-runner, so `clojure -M:test` runs the project's
  suite out of the box (the external runner builds+runs exactly this).

  With `trace?`, BOTH test aliases enter through `slopp.testmain` — the trace
  runner that WRAPS cognitect — so the external tier yields a form trace
  (#121, the only tier that runs ^:external tests). Cognitect stays in
  :extra-deps: the runner resolves it there and delegates, leaving the output
  the summary parsers read untouched. Both aliases and not one, because `done`
  runs :test-run narrowed while `commit_point` runs :test full — tracing only
  one entry leaves a hole exactly where the gate is.

  With `client-deps` (the BUILD-ONLY cljs compiler manifest, D-web-cljs), adds a
  `:cljs` alias carrying those deps + the `cljs-src` extra-path, so
  `clojure -A:cljs` resolves the ClojureScript compiler for the compile step —
  and they NEVER enter the runtime `:deps` that ships. Absent client-deps the
  alias is omitted, so output is unchanged.

  With an EMPTY manifest and no test/native/cljs aliases the output is
  byte-identical to the pre-manifest version (the build! `ours?` byte-identity
  guard relies on this)."
  ([native?] (deps-edn native? {}))
  ([native? deps] (deps-edn native? deps false))
  ([native? deps test?] (deps-edn native? deps test? false))
  ([native? deps test? trace?] (deps-edn native? deps test? trace? {}))
  ([native? deps test? trace? client-deps]
   ;; bind *print-namespace-maps* OFF: it defaults true at a REPL, false in a
   ;; script — leaving it would make output non-deterministic (the git
   ;; projection + build! ours? guard both depend on byte-stable output).
   (let [deps-str (if (seq deps)
                    (str " :deps " (binding [*print-namespace-maps* false]
                                     (pr-str (coerce-exclusions deps))))
                    "")
         main-ns  (if trace? "slopp.testmain" "cognitect.test-runner")
         ;; each alias entry is "KEY\n  {VALUE}"; the first sits right after the
         ;; aliases-map `{` (matching the historical single-:native layout), the
         ;; rest are 2-space-indented — order is deterministic (test, native, cljs).
         aliases  (cond-> []
                    test?   (conj (str ":test\n"
                                       "  {:extra-paths [\"test\"]\n"
                                       "   :extra-deps  {io.github.cognitect-labs/test-runner\n"
                                       "                 {:git/tag \"v0.5.1\" :git/sha \"dfb30dd\"}}\n"
                                       "   :main-opts   [\"-m\" \"" main-ns "\"\n"
                                       "                 \"-d\" \"test\" \"-d\" \"src\" \"-r\" \".*\"]}")
                                  ;; :test-run = same runner WITHOUT the baked -r
                                  ;; regex: -n/-v args actually narrow (the baked
                                  ;; -r unions with -n in cognitect's runner)
                                  (str ":test-run\n"
                                       "  {:extra-paths [\"test\"]\n"
                                       "   :extra-deps  {io.github.cognitect-labs/test-runner\n"
                                       "                 {:git/tag \"v0.5.1\" :git/sha \"dfb30dd\"}}\n"
                                       "   :main-opts   [\"-m\" \"" main-ns "\"\n"
                                       "                 \"-d\" \"test\" \"-d\" \"src\"]}"))
                    native? (conj (str ":native\n"
                                       "  {:extra-paths [\"classes\"]\n"
                                       "   :extra-deps  {com.github.clj-easy/graal-build-time {:mvn/version \"1.0.5\"}}\n"
                                       "   :jvm-opts    [\"-Dclojure.compiler.direct-linking=true\"]}"))
                    (seq client-deps)
                    (conj (str ":cljs\n"
                               "  {:extra-paths [\"cljs-src\"]\n"
                               "   :extra-deps  "
                               (binding [*print-namespace-maps* false]
                                 (pr-str (coerce-exclusions client-deps)))
                               "}")))]
     (if (empty? aliases)
       (str "{:paths [\"src\"]" deps-str "}\n")
       (str "{:paths [\"src\"]" deps-str "\n"
            " :aliases\n"
            " {" (str/join "\n  " aliases) "}}\n")))))

(defn native-script
  "build-native.sh: AOT-compile the launcher (and, transitively, the app),
  then native-image the result into `bin-name`. `asset-paths` (the file
  manifest's paths) copy into classes/ — putting them on the compile
  classpath as resources — and ride -H:IncludeResources, so the binary
  serves its own assets."
  [bin-name asset-paths]
  (let [assets (vec (sort (map str asset-paths)))
        copies (apply str
                      (for [p assets]
                        (let [dir (let [i (.lastIndexOf ^String p "/")]
                                    (when (pos? i) (subs p 0 i)))]
                          (str (when dir (str "mkdir -p \"classes/" dir "\"\n"))
                               "cp \"" p "\" \"classes/" p "\"\n"))))
        include (when (seq assets)
                  (str "  -H:IncludeResources='"
                       (clojure.string/join "|"
                                            (map #(clojure.string/replace % "." "\\.")
                                                 assets))
                       "' \\\n"))]
    (str "#!/usr/bin/env bash\n"
         "# Generated by slopp build! — compiles this project to a native binary.\n"
         "# Needs GraalVM 21+ on PATH (native-image ships inside the JDK; no gu).\n"
         "set -euo pipefail\n"
         "cd \"$(dirname \"$0\")\"\n"
         "\n"
         "command -v native-image >/dev/null 2>&1 || {\n"
         "  echo \"native-image not found — install GraalVM 21+ (e.g.\" >&2\n"
         "  echo \"mise install java@graalvm-community-21, or graalvm.org)\" >&2\n"
         "  exit 1\n"
         "}\n"
         "\n"
         "mkdir -p classes\n"
         copies
         "clojure -M:native -e \"(compile 'native.main)\"\n"
         "\n"
         "native-image \\\n"
         "  -cp \"classes:$(clojure -Spath -A:native)\" \\\n"
         "  -o \"" bin-name "\" \\\n"
         "  --no-fallback \\\n"
         include
         "  --features=clj_easy.graal_build_time.InitClojureClasses \\\n"
         "  native.main\n"
         "\n"
         "echo \"built ./" bin-name "\"\n")))

(defn compiler-coord
  "The build-only dependency coordinate [lib coord] for a client-compiler
   keyword (the compiler slopp DISPATCHES to), or nil for a backend slopp has
   no bundled default for. Only :clojurescript is implemented today; cherry /
   squint would add rows here when their backends land."
  [compiler]
  (case compiler
    :clojurescript ['org.clojure/clojurescript {:mvn/version "1.11.132"}]
    nil))
